In [1]:
from pytential.reduce.matrix_methods import _preprocess_constraints_system, compute_affine_constraint_elimination_map
import numpy as np

In [10]:
A = np.array([[1,0,1,0,-1,0,0,0], [0,1,0,1,0,-1,0,0], [1,1,0,0,0,0,-1,0], [0,0,1,1,0,0,0,-1]])
b = np.array([0, 0,0,0])

In [11]:
_preprocess_constraints_system(A,b)

(array([[ 1,  0,  1,  0, -1,  0,  0,  0],
        [ 0,  1,  0,  1,  0, -1,  0,  0],
        [ 1,  1,  0,  0,  0,  0, -1,  0],
        [ 0,  0,  1,  1,  0,  0,  0, -1]]),
 array([0, 0, 0, 0]))

In [12]:
Tmap, toffset, ind = compute_affine_constraint_elimination_map(A, b, [4,5])

In [13]:
p = np.array([.4,.6,.6,.4,1,1,1,1])
A@p-b

array([0., 0., 0., 0.])

In [14]:
Tmap@p[ind]

array([0.4, 0.6, 0.6, 0.4, 1. , 1. , 1. , 1. ])